version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      - QUEUE_CONNECTION=redis
      - DB_HOST=yoprint_db
      - DB_DATABASE=yoprint-live-upload
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
    depends_on:
      - yoprint_db
      - redis
    networks:
      - yoprint_network

  nginx:
    image: nginx:alpine
    container_name: yoprint-nginx
    restart: unless-stopped
    ports:
      - "8005:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - yoprint_network

  yoprint_db:
    image: mysql:8.0
    container_name: yoprint_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: yoprint-live-upload
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - yoprint_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - yoprint_network

volumes:
  dbdata:

networks:
  yoprint_network:
    driver: bridge
